<a href="https://colab.research.google.com/github/Andrey-Miroshnikov/dap-2024/blob/main/les03/rep.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Лабораторная работа №3
## NumPy

**Выполнил:** Мирошников Андрей Евгеньевич  
**Группа:** 12002308

### Цель работы
Освоение библиотеки NumPy для эффективных научных вычислений в Python, включая работу с многомерными массивами, векторизованными операциями и математическими функциями.

### Ход работы


Подключение библиотеки NumPy

In [ ]:
import numpy as np
print(f"Версия NumPy: {np.version.version}")

Версия NumPy: 2.0.2


Задача №1. Создать массив 10x10 со случайными значениями, найти минимум и максимум (низкая)

In [ ]:
print("\n1. Массив 10x10 с минимумом и максимумом:")
# Создаем массив с целыми числами от 0 до 99
arr_10x10 = np.random.randint(0, 100, (10, 10))
print("Массив:")
print(arr_10x10)
print(f"Минимум: {arr_10x10.min()}")
print(f"Максимум: {arr_10x10.max()}")


1. Массив 10x10 с минимумом и максимумом:
Массив:
[[11 83 79 32 46 75 89 40  1 28]
 [ 3 72 24  7 10 80  5 45 63 35]
 [ 7 62 92 63 40 23 36 57 76 71]
 [37 78 53  6 77 58 63 83 11 32]
 [10 93 34 44 93 23 96 78 17 67]
 [66  2 32 84 57 97 38 20 50 30]
 [32 57 32 77 99 94 94 63  5 65]
 [ 8  3 93 97 31 78 33 40 36 39]
 [18 12 79 72 47 20 65 91 99 56]
 [53 11 42 36 90 51 96 95 82 45]]
Минимум: 1
Максимум: 99


Задача №2. Создать 8x8 матрицу и заполнить её единицами и нулями в шахматном порядке

In [ ]:
print("\n2. Шахматная доска 8x8:")
chessboard = np.ones((8, 8), dtype=int)
chessboard[1::2, ::2] = 0
chessboard[::2, 1::2] = 0
print(chessboard)


2. Шахматная доска 8x8:
[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


Задача №3. Дан массив из 11 элементов, поменять знак у элементов, значения которых между 3 и 8

In [ ]:
print("\n3. Смена знака у элементов от 3 до 8:")
z = np.arange(11)
print("Исходный массив:", z)
z[(z > 3) & (z < 8)] *= -1
print("Измененный массив:", z)


3. Смена знака у элементов от 3 до 8:
Исходный массив: [ 0  1  2  3  4  5  6  7  8  9 10]
Измененный массив: [ 0  1  2  3 -4 -5 -6 -7  8  9 10]


Задача №4. Найти среднее заначение строки матрицы и вычесть его из каждого елемента строки

In [ ]:
print("\n4. Вычитание среднего значения строки:")
# Создаем матрицу с целыми числами от 0 до 9 для простоты
z = np.random.randint(0, 10, (5, 10))
print("Исходная матрица:")
print(z)
row_means = z.mean(axis=1, keepdims=True)
z_centered = z - row_means
print("Матрица после центрирования:")
print(z_centered)


4. Вычитание среднего значения строки:
Исходная матрица:
[[2 7 6 3 0 9 4 3 6 9]
 [2 9 1 7 6 1 8 2 8 3]
 [0 2 4 0 3 6 3 9 9 1]
 [4 5 9 0 5 8 2 0 2 7]
 [8 0 2 5 9 2 2 8 3 5]]
Матрица после центрирования:
[[-2.9  2.1  1.1 -1.9 -4.9  4.1 -0.9 -1.9  1.1  4.1]
 [-2.7  4.3 -3.7  2.3  1.3 -3.7  3.3 -2.7  3.3 -1.7]
 [-3.7 -1.7  0.3 -3.7 -0.7  2.3 -0.7  5.3  5.3 -2.7]
 [-0.2  0.8  4.8 -4.2  0.8  3.8 -2.2 -4.2 -2.2  2.8]
 [ 3.6 -4.4 -2.4  0.6  4.6 -2.4 -2.4  3.6 -1.4  0.6]]


Задача №5. Поменяйте 1 и 2 строки матрицы

In [ ]:
print("\n5. Обмен 1 и 2 строк:")
z = np.arange(25).reshape(5,5)
print("Исходная матрица:")
print(z)
z[[0, 1]] = z[[1, 0]]
print("После обмена строк:")
print(z)


5. Обмен 1 и 2 строк:
Исходная матрица:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
После обмена строк:
[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


Задача №6. Дан массив 10x2 подеставлющий собой точки в декартовой системе координат, преобразовать в полярную

In [ ]:
print("\n6. Преобразование в полярные координаты:")
# Создаем массив с простыми целыми координатами
z = np.random.randint(-5, 6, (10, 2))
print("Декартовы координаты:")
print(z)
x, y = z[:, 0], z[:, 1]
r = np.sqrt(x**2 + y**2)
theta = np.arctan2(y, x)
polar_coords = np.column_stack((r, theta))
print("Полярные координаты:")
print(polar_coords)


6. Преобразование в полярные координаты:
Декартовы координаты:
[[-4 -1]
 [-5  4]
 [ 1 -5]
 [ 5 -5]
 [ 2  2]
 [-3 -2]
 [ 5  5]
 [ 4  5]
 [-3 -1]
 [ 5 -4]]
Полярные координаты:
[[ 4.12310563 -2.89661399]
 [ 6.40312424  2.46685171]
 [ 5.09901951 -1.37340077]
 [ 7.07106781 -0.78539816]
 [ 2.82842712  0.78539816]
 [ 3.60555128 -2.55359005]
 [ 7.07106781  0.78539816]
 [ 6.40312424  0.89605538]
 [ 3.16227766 -2.8198421 ]
 [ 6.40312424 -0.67474094]]


Задача №7. Заменить максимальный элемент массива на ноль

In [ ]:
print("\n7. Замена максимума на ноль:")
z = np.random.randint(0, 100, 10)
print("Исходный массив:", z)
max_index = z.argmax()
max_value = z.max()
z[max_index] = 0
print(f"Максимальный элемент: {max_value} (индекс {max_index})")
print("После замены:", z)


7. Замена максимума на ноль:
Исходный массив: [97 15  5 74 56 14 21 23 11 94]
Максимальный элемент: 97 (индекс 0)
После замены: [ 0 15  5 74 56 14 21 23 11 94]


Задача №8. Дан массив, добавить 1 к каждому элементу с индексом, заданным в другом массиве. Добавление производиться только 1 раз

In [ ]:
import numpy as np
arr = np.random.randint(0, 10, size=10)
print("Исходный массив:")
print(arr)
indices = np.random.randint(0, 10, size=6)
print("\nИндексы, по которым нужно прибавить 1 (с повторами):")
print(indices)
unique_indices = np.unique(indices)
arr[unique_indices] += 1
print("\nМассив после прибавления 1 по уникальным индексам:")
print(arr)

Исходный массив:
[0 3 4 0 0 7 3 8 9 4]

Индексы, по которым нужно прибавить 1 (с повторами):
[4 2 2 4 4 7]

Массив после прибавления 1 по уникальным индексам:
[0 3 5 0 1 7 3 9 9 4]


Задача №9. Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [ ]:
print("\n9. Вставка трех нулей между элементами:")
z = np.array([1,2,3,4,5])
result = np.zeros(len(z) + (len(z)-1)*3)
result[::4] = z
print("Результат:", result)


9. Вставка трех нулей между элементами:
Результат: [1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


Задача №10. Найти ближайшее к заданному значению число в заданном массиве

In [ ]:
print("\n10. Поиск ближайшего числа:")
z = np.arange(100)
v = np.random.uniform(0, 100)
print("Сгенерированный массив:")
print(z)
print(f"\nИскомое значение: {v:.2f}")
idx = (np.abs(z - v)).argmin()
nearest = z[idx]
print(f"Ближайшее число: {nearest}")
print(f"Индекс ближайшего числа: {idx}")


10. Поиск ближайшего числа:
Сгенерированный массив:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]

Искомое значение: 20.92
Ближайшее число: 21
Индекс ближайшего числа: 21


## Вывод по лабораторной работе №3

В ходе выполнения лабораторной работы были успешно освоены основные возможности библиотеки NumPy для научных вычислений в Python.

**Основные достижения:**

1. **Практическое освоение создания массивов** - отработаны навыки создания массивов различных размерностей и типов данных, включая генерацию случайных данных, заполнение по шаблону и преобразование существующих структур.

2. **Решение разнообразных задач обработки данных**:
   - Поиск минимума и максимума в многомерных массивах
   - Создание структур по шаблону (шахматная доска)
   - Условное изменение элементов массива
   - Статистическая обработка данных (центрирование)
   - Манипуляции с подмассивами (перестановка строк)
   - Преобразование систем координат

3. **Изучение особенностей NumPy**:
   - Векторизованные операции и их преимущества перед циклами
   - Индексация и slicing многомерных массивов
   - Работа с уникальными значениями и обработка повторов
   - Поиск и фильтрация данных в массивах
   - Эффективное использование памяти

4. **Освоение математических операций**:
   - Поэлементные операции над массивами
   - Статистические функции (суммирование, усреднение)
   - Математические преобразования (декартовы → полярные координаты)
   - Работа с индексами и поиск элементов

Полученные знания составляют прочную основу для дальнейшего изучения научных вычислений в Python и работы с такими библиотеками как Pandas, SciPy и Scikit-learn. Эффективное использование NumPy позволяет значительно ускорить выполнение вычислительных задач и упростить работу с многомерными данными.

## Ответы на теоретические вопросы

### Вопрос 1: Какой тип (dtype) будут иметь элементы массива?

- `np.array([1, 4, 2, 5, 3])` → `int64` (целые числа по умолчанию)
- `np.array([1., 4, 2, 5, 3])` → `float64` (присутствует float, поэтому повышение до float)
- `np.array([1, 4, 2, 5, 3], dtype='float128')` → `float128` (явное указание типа)
- `np.array([1., 4, 2, 5, 3], dtype='complex128')` → `complex128` (явное указание комплексного типа)
- `np.array([1, 4, 2, 5, 3], dtype='float64')` → `float64` (явное указание типа)
- `np.array([1, 4, 2, 5, 3], dtype='int64')` → `int64` (явное указание типа)
- `np.array([1, 4, 2, 5, 3], dtype='bool')` → `bool` (0 → False, остальное → True)
- `np.array([1, 4, 2, 5, 3], dtype='str')` → `<U1` или `<U21` (строковый тип, длина зависит от платформы)
- `np.array([1, 4, 2, 5, '3'])` → `<U11` (смешанные типы → строка, самый общий тип)
- `np.array([1, -4, 2, 0, 1j])` → `complex128` (присутствует комплексное число)

### Вопрос 2: Что будет выведено в консоль и почему?

- `np.array([1, 4, 2, 5, 3], dtype='str')[1] + '1'` → `'41'`  
  **Почему**: Элемент с индексом 1 это строка '4', конкатенация с '1' дает '41'

- `np.array([1, -4, 2, 0, 3], dtype='bool')[3] or np.array([1, -4, 2, 0, 3])[1]` → `-4`  
  **Почему**: `dtype='bool'` преобразует числа: 0 → False, остальное → True. [3] = 0 → False. Операция `or` возвращает первый истинный операнд или последний. `np.array([1, -4, 2, 0, 3])[1] = -4` (True) → возвращается -4

- `np.array([1, -4, 2, 0, 3], dtype='bool')[3] and np.array([1, -4, 2, 0, 3])[1]` → `False`  
  **Почему**: [3] = 0 → False. Операция `and` возвращает первый ложный операнд → False

- `np.array([1, -4, 2, 0, True], dtype='int64')[-1]` → `1`  
  **Почему**: True преобразуется в целое число 1

- `np.array([1, -4, 2, 0, 1j], dtype='int64')[1]` → **Ошибка!**  
  **Почему**: Нельзя явно преобразовать комплексное число 1j в int64

- `np.array([1, -4, 2, 0, 1j], dtype='str')[-1]` → `'1j'`  
  **Почему**: Комплексное число преобразуется в строку '1j'

- `np.array([1, 4, 2, 5, '3'])[-1] * 3` → `'333'`  
  **Почему**: Элемент '3' это строка, умножение строки на число повторяет ее → '333'

### Вопрос 3: Каков результат операции?

- `np.ones((3, 5), dtype=float)` → Матрица 3x5 из единиц типа float64
- `np.full((3, 5), 3.14)` → Матрица 3x5, заполненная значением 3.14
- `np.linspace(0, 1, 5)` → `array([0. , 0.25, 0.5 , 0.75, 1. ])` (5 равномерно distributed точек)
- `np.diag((1,3,5))` → Диагональная матрица 3x3 с элементами 1, 3, 5 на диагонали
- `np.smile((1,3,5))` → **Ошибка!** Функция `np.smile()` не существует
- `np.random.random((3, 3))` → Матрица 3x3 со случайными числами от 0 до 1
- `np.eye(3)` → Единичная матрица 3x3
- `np.empty(3)` → Массив из 3 элементов без инициализации (значения могут быть любыми)

### Вопрос 4: Дан двумерный массив X, что будет выведено в консоль?

```python
X = np.array([[3, 5, 2, 4],
              [7, 6, 8, 8],
              [1, 6, 7, 7]])
```

- **X[0,0]** → 3 (элемент в 0 строке, 0 столбце)
- **X[-1,-1]** → 7 (элемент в последней строке, последнем столбце)
- **X[0:1,-1]** → [4] (срез: строка 0, последний столбец)
- **X[0:2,-1]** → [4 8] (строки 0 и 1, последний столбец)
- **X[0:2,0:2]** → [[3 5] [7 6]] (строки 0-1, столбцы 0-1)
- **X[1,1:3]** → [6 8] (строка 1, столбцы 1-2)
- **X[1,:]** → [7 6 8 8] (вся строка 1)
- **X[:,:]** → Вся матрица (аналог X)
- **X[:]** → Вся матрица (аналог X)
- **X[::2,::2]** → [[3 2] [1 7]] (каждая вторая строка и столбец)
- **X[0:3:2,0:3:2]** → [[3 2] [1 7]] (аналогично предыдущему)
- **X[::-1,::-1]** → [[7 7 6 1] [8 8 6 7] [4 2 5 3]] (обратный порядок строк и столбцов)

### Вопрос 5: Дан двумерный массив grid, в чем различее между операциями?
```python
grid = np.arange(16).reshape((4, 4))
```

- **np.split(grid, [2])** → Разделяет массив по строкам после индекса 2. Получится список из двух массивов: строк 0-1 и 2-3
- **np.split(grid, [2], axis=1)** → Разделяет массив по столбцам после индекса 2. Получится список из двух массивов: столбцов 0-1 и 2-3

### Вопрос 6: В чем различие между операциями?

- **[1, 2, 3] + [3, 2, 1]** → [1, 2, 3, 3, 2, 1] (конкатенация списков)
- **np.array([1, 2, 3]) + np.array([3, 2, 1])** → [4 4 4] (поэлементное сложение массивов)

### Вопрос 7: Как в Colab измерить время выполнения кода?

В Google Colab используются команды:

- **%time** → Измеряет время выполнения одной строки кода
- **%timeit** → Многократно выполняет код и возвращает усредненное время выполнения

**Пример**: %timeit np.sum(np.arange(1000))

### Вопрос 8: Дан массив X, каковы результаты операций?
 ```python
 M = np.array([[3, 5, 2, 4],
              [7, 6, 8, 8],
              [1, 6, 7, 7]])
```

- **np.sum(M)** → 58 (сумма всех элементов)
- **np.sum(M, axis=1)** → [14 29 21] (сумма по строкам)
- **np.sum(M, axis=0)** → [11 17 17 19] (сумма по столбцам)
- **np.sum(M, axis=2)** → Ошибка! Ось 2 не существует (массив 2D)
- **np.sum(M, 1)** → [14 29 21] (аналог axis=1)
- **sum(M)** → [11 17 17 19] (для 2D массивов эквивалентно sum(M, axis=0))
- **sum(M,1)** → Ошибка! Функция sum() не принимает второй аргумент в таком виде

### Вопрос 9: Дан массив X, что будет выведено в консоль?

Массив X: [1 2 3 4]

- **X > 3** → [False False False True] (поэлементное сравнение)
- **X < 3** → [True True False False] (поэлементное сравнение)
- **X[X < 3]** → [1 2] (булева индексация - элементы, где условие True)
- **X[X > 3]** → [4] (булева индексация)
- **X[X != 3]** → [1 2 4] (булева индексация)

### Вопрос 10: В чем преимущество массивов NumPy по сравнению с обычными списками? Чем обусловлено это преимущество?

**Преимущества NumPy**:
- Высокая производительность (в 10-100 раз быстрее операций с списками)
- Векторизованные операции - возможность выполнять математические операции над всем массивом без циклов
- Эффективное использование памяти - данные хранятся в непрерывных блоках памяти
- Многомерные массивы - удобная работа с матрицами и тензорами
- Широкий набор математических функций - оптимизированные реализации математических операций
- Интеграция с научными библиотеками - совместимость с pandas, scikit-learn, matplotlib и др.

**Причины высокой производительности**:
- Непрерывное хранение данных в памяти (в отличие от разрозненных объектов в списках)
- Векторизованные операции на C/Fortran - низкоуровневая оптимизация
- Отсутствие накладных расходов на проверку типов элементов при операциях
- Кэш-дружественная организация данных - эффективное использование кэша процессора
- Использование SIMD-инструкций процессора для параллельных вычислений